DError: update names and document them more
Changed the name of DErrorCode's to look better, they felt too verbose before.

Also documented them more, so it's easier to read over them when raising parser error.